### ISSUE TITLE
PAWN PROMOTE bug

### ISSUE THREAD

**Issue by CodaCodr** [prashanthselvam/crazychess#3]
When a white pawn is taking a black rook and thereby being promoted, a modal dialog appears saying "PAWN PROMOTE" with now discoverable means to proceed.

I tried hiding the overlay but still no way to proceed.

![image](https://user-images.githubusercontent.com/436812/121898856-73f7d480-cce9-11eb-8d9a-598507fee353.png)

**Comment by CodaCodr** [comment]
Same again:

![image](https://user-images.githubusercontent.com/436812/121900066-9e965d00-ccea-11eb-8b09-d7b1327de76b.png)

**Comment by gpukys** [comment]
Same issue. Was going to destroy the PC :(

**Comment by prashanthselvam** [comment]
Thanks for reporting this and sorry it took me so long to get to it. Was a very simple fix: https://github.com/prashanthselvam/rxjchess/commit/dd3d8e1cc6bfea7f34e645dbe459f191ff60d841
